require "lib_c"
require "primitives"
require "c/stddef"
require "intrinsics"

require "./char"
require "./enum"
require "./float"
require "./int"
require "./loop"
require "./nil"
require "./number"
require "./object"
require "./pointer"
require "./proc"
require "./range"
require "./slice"
require "./static_array"
require "./string"

require "./errno"
require "./exception"
require "./panic"

require "./main"
